apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 035087637971.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 035087637971.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 0ba40fa3
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
